CREATE OR REPLACE FUNCTION obterDadosConsultaPorId( p_consultaId IN NUMBER)
RETURN SYS_REFCURSOR IS
    l_cursor SYS_REFCURSOR;
BEGIN 
    OPEN l_cursor FOR
        SELECT A.CONSULTAID, A.MEDICOID, A.PACIENTEID, A.DATACONSULTA,
               B.NOME_PACIENTE AS NOME_PACIENTE, C.NOME_MEDICO AS NOME_MEDICO
        FROM CONSULTAS A
        INNER JOIN PACIENTE B
            ON A.PACIENTEID = B.PACIENTEID
        INNER JOIN MEDICO C
            ON A.MEDICOID = C.MEDICOID
        WHERE A.CONSULTAID = p_consultaId;

    RETURN l_cursor;
END;